name: "fount-charCI"
description: "run CI on fount character"
branding:
  color: "black"
  icon: "activity"
inputs:
  CI-filepath:
    description: "CI file path for testing your character"
    required: true
  github-token:
    description: "github token"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - run: git clone --depth 1 --branch master https://github.com/steve02081504/fount.git ./fount
      shell: bash
    - run: cp -r $GITHUB_ACTION_PATH/default_data ./fount/data
      shell: bash
    - uses: actions/checkout@v4
      with:
        path: ./fount/data/users/CI-user/chars/CI-char
    - uses: denoland/setup-deno@v2
      id: deno
      with:
        deno-version: vx.x.x
        cache: true
    - uses: actions/cache@v4
      with:
        path: ./node_modules
        key: fount-charCI-node-modules
    - run: |
        deno run --allow-scripts --allow-all --node-modules-dir=auto $GITHUB_ACTION_PATH/index.mjs ${{ inputs.CI-filepath }}
      shell: bash
    - name: Delete Previous Cache # 删除之前的缓存确保缓存随着项目运行而更新
      continue-on-error: true
      shell: bash
      working-directory: ./fount/data/users/CI-user/chars/CI-char
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete "fount-charCI-node-modules" --confirm
        gh actions-cache delete "deno-cache-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-${{ hashFiles('**/deno.lock') }}" --confirm
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    - name: Save Cache
      uses: actions/cache/save@v4
      with:
        path: ./node_modules
        key: fount-charCI-node-modules
    - name: get deno dir
      shell: bash
      run: echo "DENO_DIR=$(deno info --json | jq -r '.denoDir')" >> $GITHUB_ENV
    - name: Save Cache
      uses: actions/cache/save@v4
      with:
        path: ${{ env.DENO_DIR }}
        key: deno-cache-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-${{ hashFiles('**/deno.lock') }}
